identity:
  schemas:
    - id: customer
      url: file:///app/customer.schema.json
    - id: admin
      url: file:///app/admin.schema.json
  default_schema_id: customer

selfservice:
  default_browser_return_url: https://auth.local.gd/
  flows:
    logout:
      after:
        default_browser_return_url: https://auth.local.gd
    registration:
      ui_url: https://auth.local.gd/ui/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

    login:
      lifespan: 10m
      ui_url: https://auth.local.gd/ui/login
    verification:
      ui_url: https://auth.local.gd/ui/verify
      after:
        default_browser_return_url: https://auth.local.gd
      use: code
      enabled: true

    recovery:
      enabled: true
      ui_url: https://auth.local.gd/ui/recovery
      use: code
    error:
      ui_url: https://auth.local.gd/ui/error
    settings:
      ui_url: https://auth.local.gd/ui/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

  methods:
    link:
      enabled: true
    code:
      mfa_enabled: true
      config:
        lifespan: 15m
    password:
      enabled: true
      config:
        min_password_length: 8
        identifier_similarity_check_enabled: true
    totp:
      enabled: true
    lookup_secret:
      enabled: true

  allowed_return_urls:
    - https://backend.local.gd

courier:
  delivery_strategy: smtp
  sms:
    enabled: true
    request_config:
      url: https://api.twillio.com/sms/send
      method: ""
      body: file:///app/sms-mfa.jsonnet
      auth:
        type: api_key
        config:
          name: ""
          value: ""
          in: header

  channels:
    - id: sms
      request_config:
        method: ""
        body: file:///path/to/body.jsonnet
        auth:
          type: api_key
          config:
            name: ""
            value: ""
            in: header
        url: https://example.com/api/v1/email
      type: http

serve:
  public:
    cors:
      enabled: false
      allowed_origins:
        - https://auth.local.gd
    base_url: https://auth.local.gd
    host: "0.0.0.0"
    port: 4433
    request_log:
      disable_for_health: true
  admin:
    base_url: http://kratos:4434/
    host: "0.0.0.0"
    port: 4434
    request_log:
      disable_for_health: true

hashers:
  algorithm: argon2

session:
  earliest_possible_extend: 1h
  whoami:
    required_aal: highest_available
