import path from 'path';
import { NestFactory } from '@nestjs/core';
import { Logger } from 'nestjs-pino';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { NestExpressApplication } from '@nestjs/platform-express';
import consolidate from 'consolidate';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule, {
    bufferLogs: true,
    rawBody: true,
  });
  app.useLogger(app.get(Logger));

  // Trust X-Forwarded-* headers
  app.set('trust proxy', true);

  // Enable Nunjucks
  app.engine('njk', consolidate.nunjucks);
  app.setBaseViewsDir(path.join(__dirname, 'views'));
  app.useStaticAssets(path.join(__dirname, 'public'));

  app.setViewEngine('njk');

  const config = new DocumentBuilder()
    .setTitle('Backend')
    .setDescription('Backend')
    .setVersion('1.0')
    .build();

  // Load Swagger metadata from the metadata file generated by NestJS CLI
  // Make sure that the metadata file does not block app start up
  /* eslint-disable import/no-unresolved,@typescript-eslint/ban-ts-comment */
  // @ts-ignore
  await import('./metadata')
    .then(async (metadata) => {
      await SwaggerModule.loadPluginMetadata(metadata.default);
    })
    .catch((e) => {
      console.error('Error loading metadata', e);
    });
  /* eslint-enable import/no-unresolved,@typescript-eslint/ban-ts-comment */

  // await SwaggerModule.loadPluginMetadata(metadata);
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('docs', app, document);

  await app.listen(process.env.PORT || 8080);
}
bootstrap();
