import path from 'path';
import { NestFactory } from '@nestjs/core';
import { Logger } from 'nestjs-pino';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { NestExpressApplication } from '@nestjs/platform-express';
import consolidate from 'consolidate';
import { AppModule } from './app.module';
import { RedocModule } from '@/libs/redoc/redoc.module';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule, {
    bufferLogs: true,
    rawBody: true,
  });
  const logger = app.get(Logger);
  app.useLogger(logger);

  // Trust X-Forwarded-* headers
  app.set('trust proxy', true);

  // Enable Nunjucks
  app.engine('hbs', consolidate.handlebars);
  app.setBaseViewsDir(path.join(__dirname, 'views'));
  app.useStaticAssets(path.join(__dirname, 'public'), {
    prefix: '/public/',
  });
  app.setViewEngine('hbs');

  // Enable Swagger
  const config = new DocumentBuilder()
    .setTitle('Backend')
    .setDescription('Backend')
    .setVersion('1.0')
    .build();

  // Load Swagger metadata from the metadata file generated by NestJS CLI
  // Make sure that the metadata file does not block app start up
  // since it's not checked into Git
  /* eslint-disable import/no-unresolved,@typescript-eslint/ban-ts-comment */
  // @ts-ignore
  await import('./metadata')
    .then(async (metadata) => {
      await SwaggerModule.loadPluginMetadata(metadata.default);
    })
    .catch((e) => {
      console.error('Error loading metadata', e);
    });
  /* eslint-enable import/no-unresolved,@typescript-eslint/ban-ts-comment */

  // await SwaggerModule.loadPluginMetadata(metadata);
  const document = SwaggerModule.createDocument(app, config);
  // SwaggerModule.setup('docs', app, document);
  await RedocModule.setup('/docs', app, document, {
    auth: {
      enabled: true,
      user: 'admin',
      password: 'admin',
    },
  });

  await app.listen(process.env.PORT || 8080);
  logger.log(`Application is running on: ${await app.getUrl()}`);
}

bootstrap();
